### ISSUE TITLE
Create a new project with randomized name!

### ISSUE THREAD

**Issue by wmstack** [publictheta/vscode-create-project#1]
Currently, the extension requires users to specify a project name when creating a new project. This process can go against the spirit of quickly creating projects, which I believe is one of the main goals of this extension. This is how some `npm create` commands work, creating a random name by default.

To align with that goal, I propose adding a feature that allows users to generate a project with a randomized double-word name, which might be optionally selected, the same way as this:
<img width="715" alt="image" src="https://github.com/user-attachments/assets/0ebd3406-df51-4882-bfaf-ccd43258d266">

Alternatively, it could just create a random two word name and put it in the default folder without prompting, or have a prompt with only the name instead of the full-path.

Finally I noticed that often in the explorer the Java extension has a button to create a new project:
<img width="306" alt="image" src="https://github.com/user-attachments/assets/ffa0f2c5-cd59-48b4-b15d-ad0ab9de939b">

I was wondering what the API for that is, as it would be nice to have a similar button for creating a project here.

**Comment by publictheta** [comment]
Thank you for your feedback!

There are some concerns regarding random name generation, especially the need for a word dictionary, which could increase the size of the extension, the warm-up time, and maintenance costs. I'll investigate them later, and if it seems acceptable, I'd like to add this feature. (That said, I expect it will be fine, since [`friendly-words`] by Glitch is around 50KB for example.)

[`friendly-words`]: https://github.com/glitchdotcom/friendly-words

Regarding the UI, I'd like to keep the current behavior of asking for a project name. So, my current plan is simply replacing the current `untitled` with a randomly generated name, and if it's useful to have a feature to create a random name project without any prompt, adding it as another command (e.g., `Create Project with Random Name`).

For the other ideas, such as using a name-only input (#2) or adding a button to the explorer (#3), I'd like to open separate issues to consider them further as they could be improvements to the overall UI of the extension.

If you have any thoughts on these, please feel free to reply here or the new issues. Thank you!

**Comment by wmstack** [comment]
Oh thanks for considering my proposal. I don't have much to add here other than I think glitch looks promising. As far as I know, the words should be of the form "predicate-object" according to my cursory look at the `friendly-words` package.

Since there is a potential for a one or two more commands, it could be helpful to discuss which one is going to be executed by the explorer button.

**Comment by publictheta** [comment]
Thank you for the PR!

I was actually about to try implementing it in almost the same way, so this is very helpful!

I'd like to think a little more about the UI, including adding settings, so for now, I'll merge your code and release it as a new version as soon as possible.
